/** Tunables for chat moderation (single + cross-message). */
export const MODERATION_CONFIG = Object.freeze({
  HISTORY_MAX_MESSAGES: 10,
  CONTEXT_WINDOW_MS: 120_000,
  MIN_SPLIT_DIGIT_LEN: 7,
  STRONG_DIGIT_MERGE_LEN: 10,
  RAPID_FRAGMENT_WINDOW_MS: 50_000,
  RAPID_FRAGMENT_MAX_LEN: 6,
  RAPID_FRAGMENT_MIN_COUNT: 3,
  CONTEXT_BLOCK_RISK_SCORE: 75,
  SESSION_BLOCKS_FOR_LOCK: 3,
  CHAT_LOCK_DURATION_MS: 60_000,
});
